# Identificación de la aplicación (¡Importante para Eureka!)
spring.application.name=organizaciones-service

# Puerto del servicio (evitar choques, municipalidades usa el 8080 por defecto si no lo cambiaron, pongamos 8082 por ejemplo)
server.port=8089

# Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mascotas_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Seguridad OAuth2 (Auth0)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-i56p7npkqe6uyumd.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.sanosysalvos.com

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
