spring.application.name=notificaciones
server.port=8082

#Datos de la librebria para mandar correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=cuentasvminecraft2026fmjn@gmail.com
spring.mail.password= bjso saqq xjej igsi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.datasource.url=jdbc:postgresql://localhost:5434/notificaciones-db
spring.datasource.username=admin-noti
spring.datasource.password=password-noti
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.security.user.name=admin
spring.security.user.password=admin123

# Configuracion de kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mascotas-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
