spring.application.name=usuarios-perm
server.port=8087
spring.datasource.url=jdbc:postgresql://localhost:5436/usuarios_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-i56p7npkqe6uyumd.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.sanosysalvos.com

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
