spring.application.name=mascotas-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/mascotas_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-i56p7npkqe6uyumd.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.sanosysalvos.com

# Kafka Configuration (para conectar con el Docker)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mascotas-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

google.maps.api.key=AIzaSyCBAVEG77dkNarzBfJ_lOz0Z1369G4Dnqc