# Identificación de la aplicación (¡Importante para Eureka!)
spring.application.name=municipalidades-service
server.port=8082

# Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/mascotas_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Seguridad OAuth2 (Auth0)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-i56p7npkqe6uyumd.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.sanosysalvos.com

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true

# Configuracion Jackson - Fechas como texto ISO (yyyy-MM-dd), no como timestamps
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# Permitir carga de archivos grandes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
