spring.application.name=municipalidades-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-i56p7npkqe6uyumd.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://api.sanosysalvos.com
